export type LookState = {
    aoIntensity: number;
    aoRadius: number;
    sunAzimuth: number;
    sunElevation: number;
    sunIntensity: number;
    shadowSoftness: number;
    shadowOpacity: number;
    skyColor: string;
    groundBounce: string;
    skyIntensity: number;
    sunColor: string;
    cameraZoom: number;
    cameraAzimuth: number;
    cameraElevation: number;
    panX: number;
    panZ: number;
    zoomMin: number;
    zoomMax: number;
    zoomReferenceWidth: number;
    ground: string;
    road: string;
    grass: string;
    wall: string;
    roof: string;
    accent: string;
    yellow: string;
    cardboard: string;
    tree: string;
    tire: string;
    aoColor: string;
    setLook: (patch: Partial<LookState>) => void;
    zoomBy: (delta: number) => void;
    rotateBy: (deg: number) => void;
    resetView: () => void;
};
export declare const lookDefaults: {
    aoIntensity: number;
    aoRadius: number;
    sunAzimuth: number;
    sunElevation: number;
    sunIntensity: number;
    shadowSoftness: number;
    shadowOpacity: number;
    skyColor: string;
    groundBounce: string;
    skyIntensity: number;
    sunColor: string;
    cameraZoom: number;
    cameraAzimuth: number;
    cameraElevation: number;
    panX: number;
    panZ: number;
    zoomMin: number;
    zoomMax: number;
    zoomReferenceWidth: number;
    ground: string;
    road: string;
    grass: string;
    wall: string;
    roof: string;
    accent: string;
    yellow: string;
    cardboard: string;
    tree: string;
    tire: string;
    aoColor: string;
};
export type LookPatch = Partial<Omit<LookState, 'setLook' | 'zoomBy' | 'rotateBy' | 'resetView'>>;
export type ViewHome = {
    cameraZoom: number;
    cameraAzimuth: number;
    cameraElevation: number;
};
/** Remember the framing `resetView` should restore (last `activateScene`). */
export declare function setViewHome(home: Partial<ViewHome>): void;
export declare function getViewHome(): ViewHome;
export declare function applyLook(patch: LookPatch): void;
export declare const useLook: import("zustand").UseBoundStore<import("zustand").StoreApi<LookState>>;
//# sourceMappingURL=look.d.ts.map